=== GongJingYu/Winter/xml/src/main/resources/book.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT books (book*)>
<!ELEMENT book (author,name,price)>
<!ATTLIST book id CDATA #REQUIRED>
<!ELEMENT author (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT price (#PCDATA)>

=== GongJingYu/Winter/xml/src/main/resources/book.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE books SYSTEM "src\book.dtd">
<books>
    <book id="1">
        <author>gjy</author>
        <name>爱你的日子里</name>
        <price>30￥</price>
    </book>
    <book id="2">
        <author>gjy</author>
        <name>爱你的日子里</name>
        <price>30￥</price>
    </book>
</books>
